export { default as Hero } from './Hero'
export { default as Navbar } from './Navbar'
export { default as Experience } from './Experience'
export { default as Projects } from './Projects'
export { default as Contact } from './Contact'
